services:
  db:
    image: postgres:latest
    container_name: urlShortener
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local